# rumqttd broker configuration
id = 0

# Router configuration
[router]
id = 0
max_connections = 100
max_outgoing_packet_count = 100
max_segment_size = 104857600
max_segment_count = 10

# MQTT v4 configuration
[v4.1]
name = "v4-1"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1

[v4.1.connections]
connection_timeout_ms = 60000
max_payload_size = 102400
max_inflight_count = 100
dynamic_filters = true

# Console for runtime management
[console]
listen = "127.0.0.1:3030"